
package com.beitech.informamos.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculateTotalValue", targetNamespace = "http://ws.informamos.beitech.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculateTotalValue {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "total", targetNamespace = "http://ws.informamos.beitech.com/", className = "com.beitech.informamos.ws.Total")
    @ResponseWrapper(localName = "totalResponse", targetNamespace = "http://ws.informamos.beitech.com/", className = "com.beitech.informamos.ws.TotalResponse")
    @Action(input = "http://ws.informamos.beitech.com/CalculateTotalValue/totalRequest", output = "http://ws.informamos.beitech.com/CalculateTotalValue/totalResponse")
    public double total(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
